### ISSUE TITLE
Diseño de RegEmployee.aspx

### ISSUE THREAD

**Issue by darkzense** [TonnyMontenegro/Lab1WebForms#1]
Esto es lo que tengo
![image](https://user-images.githubusercontent.com/82670759/133373408-6b22680f-1e63-4d02-8281-70b79a99f66f.png)

Esto es lo que quiero lograr
![image](https://user-images.githubusercontent.com/82670759/133373447-5b27e854-964d-4a8d-9fc6-5d84380f8886.png)

También sería bueno utilizar ese esquema para RegStd si es posible, sino es mejor concentrarse en el Lab2

**Comment by TonnyMontenegro** [comment]
Problema de GUI solucionado
![issue1](https://user-images.githubusercontent.com/52424785/133530653-a68f5278-2aed-4d1b-b81e-ae04616f8bce.jpg)


También es responsivo
![issue1responsive](https://user-images.githubusercontent.com/52424785/133530658-be7965c6-eb18-49ed-a135-6a2fc7b2bcfd.jpg)

quedo a la espera de tu validación y cerrar este issue
